name: Build and Deploy Python Azure Functions

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.10'
  FUNCTION_APP_NAME: 'emos-function'
  AZURE_RESOURCE_GROUP: 'emos-rg'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt --target=".python_packages/lib/site-packages"

      - name: Prepare deployment package
        run: |
          rm -rf deploy_package
          mkdir deploy_package
          cp -r ./* ./.* deploy_package/ 2>/dev/null || true
          cd deploy_package
          zip -r ../deploy.zip . -x "*.pyc" "*/__pycache__/*" "venv/*" ".git/*" ".github/*"
          cd ..

      - name: Upload deployment package artifact
        uses: actions/upload-artifact@v4
        with:
          name: functionapp-package
          path: deploy.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download deployment package artifact
        uses: actions/download-artifact@v4
        with:
          name: functionapp-package
          path: .

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Verify Function App Configuration
        run: |
          az functionapp config appsettings set \
            --name ${{ env.FUNCTION_APP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --settings "AzureWebJobsStorage=${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}"
          az functionapp config set \
            --name ${{ env.FUNCTION_APP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --linux-fx-version "Python|3.10"

      - name: Deploy to Azure Function App
        run: |
          for attempt in {1..3}; do
            echo "Deployment attempt $attempt..."
            if az functionapp deployment source config-zip \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
              --name ${{ env.FUNCTION_APP_NAME }} \
              --src ./deploy.zip --timeout 600; then
              echo "Deployment succeeded"
              break
            else
              echo "Deployment attempt $attempt failed. Retrying in 10 seconds..."
              sleep 10
            fi
          done

      - name: Restart Function App
        run: |
          az functionapp restart \
            --name ${{ env.FUNCTION_APP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }}

      - name: Azure Logout
        run: az logout
