# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - emos-functions-v2

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'TriggerPrediction' # Matches the actual function app directory
  PYTHON_VERSION: '3.10' # Matches the runtime

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Purge pip cache
        run: pip cache purge

      - name: Install dependencies
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          # Install dependencies from the root requirements.txt
          if [ -f "requirements.txt" ]; then
            echo "Installing dependencies from root requirements.txt"
            python -m pip install --upgrade pip
            pip install --no-cache-dir -r requirements.txt --target="${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/.python_packages/lib/site-packages" --platform manylinux2014_x86_64 --only-binary=:all:
            pip check
            pip list
          else
            echo "Error: requirements.txt not found in root directory!"
            exit 1
          fi
          # Navigate to function app directory for further steps
          if [ -d "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}" ]; then
            cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
            echo "Changed to directory: $(pwd)"
          else
            echo "Error: Directory ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }} not found!"
            exit 1
          fi

      - name: Zip artifact for deployment
        run: |
          if [ -d "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}" ]; then
            cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
            zip -r ../release.zip . -x "*.pyc" "*/__pycache__/*" "venv/*"
          else
            echo "Error: Directory ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }} not found!"
            exit 1
          fi

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

      - name: Debug secrets
        run: |
          echo "Publish Profile Secret Set: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE != '' }}"

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'emos-functions-v2'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

      - name: Logout
        run: echo "No login required with publish profile"
        if: always()
