name: Deploy to Azure Function App - emos-functions-v2 (OIDC)

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read  # required to checkout the repo    

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'TriggerPrediction'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Prepare zip with host.json at root
        run: |
          mkdir -p /tmp/deploy
          cp host.json /tmp/deploy/
          cp -r ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/* /tmp/deploy/
          cd /tmp/deploy
          zip -r release.zip .
          mv release.zip $GITHUB_WORKSPACE/

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Function App
        run: |
          az functionapp deployment source config-zip \
            --name emos-functions-v2 \
            --resource-group <YOUR_RESOURCE_GROUP_NAME> \
            --src release.zip
