name: Deploy to Azure Function App - emos-functions-v2 (OIDC)

on:
  push:
    branches: [main]

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'TriggerPrediction'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Zip Function App package
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          zip -r ../release.zip . -x "*.pyc" "*/__pycache__/*"

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Function App
        run: |
          az functionapp deployment source config-zip \
            --name emos-functions-v2 \
            --resource-group voiceofthegame1-rg \
            --src release.zip
