name: Deploy Azure Function App - emos-functions-v2

on:
  push:
    branches: [ main ]

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'TriggerPrediction'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Zip Function App package
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          zip -r ../release.zip . -x "*.pyc" "*/__pycache__/*"

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'emos-functions-v2'  # Make sure this matches your Function App in Azure
          package: release.zip
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
